### ISSUE TITLE
Docs should note that debugger only works with VSCode x64

### ISSUE THREAD

**Issue by SmerkyG** [vshaxe/hashlink-debugger#10]
The documentation (as shown in both github and the marketplace) do not state that the hashlink debugger works only with the x64 build of VSCode. Maybe just add a line saying that to the top of the README.md - if you run it in the 32 bit VSCode on Windows it simply fails to debug with an unspecified error.

**Comment by Gama11** [comment]
Interesting... Probably nobody has noticed that so far!

**Comment by ncannasse** [comment]
I did notice when I tried to setup my computer for Haxe Summit :) 
Please note that this mostly concerns people having old VSCode installs since the update only update from 32 to 32. It requires uninstalling VSCode32 to install VSCode64.
