### ISSUE TITLE
Slow debugger

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/hashlink-debugger#100]
Following #97, the debugger is now very very slow. Might be related to the build of native libraries or some other change. I don't think the debugger code itself is responsible for the change in performances.

**Comment by rcstuber** [comment]
Since `deasync` messes with the event loop, it might be a good candidate for such issues?

**Comment by ncannasse** [comment]
@rcstuber tell me if you can confirm by printing a complex value (like a map or array with lots of values) if it's a lot slower with latest ffi-napi VS previous version (might require to downgrade node as well). I think this can be reproduced with nodejs commandline version (without any VSCode)

**Comment by rcstuber** [comment]
Sorry I didn't have time yet to test this. I can however confirm that it's currently horribly slow to query class fields (i.e. h2d.Object base) and that the old version I'm running trough the "debugServer" option is much faster (it does not run in Electron's node service though, but a normal `Node` process)

**Comment by rcstuber** [comment]
Seems like with the latest Electron / Node runtimes the ffi api broke again. I could make it run by upgrading packages like below and rebuilding the extension dependencies. However when hitting a breakpoint in VSCode (MacOS) the app freezes. Running the standalone adapter through node still works.

```json
    "ffi-napi": "^4.0.3",
    "ref-napi": "^3.0.3",
    "ref-struct-napi": "^1.1.1",
```

**Comment by rcstuber** [comment]
Nevermind my previous comment regarding updating npm packages, I was on an outdated commit, however the debugger still freezes when hitting a breakpoint on MacOS with VSCode's electron version being `12.0.13`. Standalone adapter running inside normal `node` still works.

**Comment by ncannasse** [comment]
This was indeed a bug with recent node versions when marshalling typed arrays between the JS context and the native library. We fixed that by implementing our own native extension (in hldebug-wrapper) that returns data using strings (sadly) so there's no big slowdown being done by nodejs. v1.3.0+ includes this fix.
