### ISSUE TITLE
mac vscode 1.11 does not support

### ISSUE THREAD

**Issue by ocd-lab** [vshaxe/hashlink-debugger#102]
![image](https://user-images.githubusercontent.com/79586594/132099486-bfcbc16c-3ef4-4571-a1c6-017fb4417121.png)
but hashlink newest version is 1.11.0
![image](https://user-images.githubusercontent.com/79586594/132099516-76c772b3-c77b-4002-a519-44f382f748bf.png)

**Comment by rcstuber** [comment]
You need to use the Github master version of Hashlink, the release binary is outdated.
