### ISSUE TITLE
Could not start debugger on port 6112

### ISSUE THREAD

**Issue by ClintFlames** [vshaxe/hashlink-debugger#110]
![i](https://user-images.githubusercontent.com/41988734/162944745-21ca344e-6f2c-4825-af81-50ca425c90b2.png)
Code is correct i checked it with:
`haxe compile.hxml` and `hl build.hl`
I have no idea what is wrong.

**Comment by Devyatyi9** [comment]
Do you use version of extension 1.3.2?

**Comment by ClintFlames** [comment]
Yes, but i doesn't see update. I also checked it on [marketplace](https://marketplace.visualstudio.com/items?itemName=HaxeFoundation.haxe-hl) and it says that current version is 1.3.2

**Comment by Devyatyi9** [comment]
Well, you can use [github version](https://github.com/vshaxe/hashlink-debugger#building-from-source) from master branch, i think it will works for you

**Comment by ClintFlames** [comment]
Looks like it helped me, thank you.
