### ISSUE TITLE
incorrect error message: "Please use a Haxe configuration that targets HashLink (found target "js" instead)."

### ISSUE THREAD

**Issue by tromero** [vshaxe/hashlink-debugger#113]
I set up my compile hxml to build both hl and js at the same time. It resulted in the error: `Please use a Haxe configuration that targets HashLink (found target "js" instead).`, unless i comment out my js build args. 

This is probably not the best approach (i haven't figured out a way to make the config change which target gets built other than having two compile hxml files, recommendations would be appreciated), but seems like the debugger should have worked with this simple setup.

my compile.hxml looks like this:

```
--class-path src
-lib heaps
--dce full

--each

# desktop
-lib hldx
# -lib hlsdl
-hl bin/stickychunks.hl
-main Main
-debug

--next

# web
-js bin/stickychunks.js
-main Main
-debug
```

and launch.json:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch Chrome against localhost",
			"url": "file://${workspaceFolder}/index.html",
			"webRoot": "${workspaceFolder}",
			"preLaunchTask": {
				"type" : "haxe",
				"args" : "active configuration"
			}
		}
		,
		{
            "name": "HashLink",
            "request": "launch",
            "type": "hl",
            "cwd": "${workspaceFolder}",
            "preLaunchTask": {
                "type": "haxe",
				"target" : "${workspaceFolder}/bin/stickychunks.hl",
                "args": "active configuration"
            }
		}
	]
}
```

**Comment by tromero** [comment]
The issue also does not occur if the .hl file is the last output in compile.hxml.

**Comment by jrdoughty** [comment]
Did this ever get resolved, I have it as well

**Comment by ncannasse** [comment]
You can instead have:
- a `common.hxml` file
- a `compile_hl.hxml` and `compile_js.hxml`  that both have `common.hxml` as their first line, thus having the same definitions in common.
- you can switch between compile_hs and compile_js in the blue bar at the bottom of VSCode to switch compilation configuration.
