### ISSUE TITLE
mac m1 cant build and use on the vscode

### ISSUE THREAD

**Issue by hnhhzy** [vshaxe/hashlink-debugger#115]
mac m1 cant build and use on the vscode

**Comment by onehundredfeet** [comment]
Seconded.  I've tried to look into it, but the best I can see is that the hashlink debugger is waiting to recv commands and the vscode side is spinning waiting for the first breakpoint.

**Comment by yuxiaomao** [comment]
Will not fix, see https://github.com/vshaxe/hashlink-debugger/issues/119#issuecomment-1512431858
