### ISSUE TITLE
Mauvais affichage d'un float dans godmode

### ISSUE THREAD

**Issue by Fl0xer** [vshaxe/hashlink-debugger#12]
Dans la classe TradingPost, si je mets un break point sur le return final de la fonction, l'affichage de la variable v avec le debugger n'est pas bonne. Je t'ai mis un commentaire dans la fonction si besoin d'une repro.

**Comment by ncannasse** [comment]
Still reproducible with latest debugger fixes

**Comment by ncannasse** [comment]
The fix is partial: the debugger needs to change block to detect that the variable has changed register storage. Needs one more fix at debugger level.
