### ISSUE TITLE
Breakpoints are broken when allowEvalCalls = true

### ISSUE THREAD

**Issue by Speedphoenix** [vshaxe/hashlink-debugger#121]
When in a breakpoint, Step Over (F10) tends to skip many lines, and other breakpoints are often skipped as well.
This apparently also triggers `Access Violation` errors.

Going manually in the adapter.js file and changing allowEvalCalls to false fixes this

**Comment by ncannasse** [comment]
Fixed with latest release (disabled by default). Will have to work more on that.
