### ISSUE TITLE
Hashlink Debugger with VS Code 1.82

### ISSUE THREAD

**Issue by Falagard** [vshaxe/hashlink-debugger#123]
I'm having problems getting HashLink Debugger to work with VS Code 1.82 (the lates version). 

Downgrading to VS Code 1.81 fixed the problem.

The Haxe extension had a problem with the latest VS Code 1.82 breaking something in communicating with the compilation server, not sure if related. 

https://github.com/vshaxe/vshaxe/issues/602

**Comment by ncannasse** [comment]
This was unrelated to vshaxe issue but I have found and fixed the problem and pushed a new version ;)
