### ISSUE TITLE
Failed to connect on debug port

### ISSUE THREAD

**Issue by Yanrishatum** [vshaxe/hashlink-debugger#17]
VSHaxe/Hashlink-Debugger: Store versions
Haxe tested: Haxe4-preview4, and latest git (80334fec8).
HL: 1.6.0
OS: Win10 x64
Log:
```
0> src/HLAdapter.hx:43: initialize
0> src/HLAdapter.hx:59: launch
0> src/HLAdapter.hx:206: start process
0> src/HLAdapter.hx:215: Running: hl --debug-wait --debug 6112 out.hl
0> src/HLAdapter.hx:280: load module
0.2> src/HLAdapter.hx:283: connecting at port 6112
0.2> hack.hx:1: 4:3371
ERROR : Failed to connect on debug port
```
It never connects to application, instantly saying that it failed to connect (which is false, because it does connect, but receives wrong data). I tinkered with output log for a bit and found that it fails at that point:
https://github.com/HaxeFoundation/hashlink/blob/master/other/debugger/hld/JitInfo.hx#L84-L86
It receives 4 while expecting 3371 (or 3/301 without heaps/hldx). The value seem to be the amount of hdlls loaded, because without hldx library it sends 3. 
Minimal reproduction code with Heaps and HLDX (so application would maintain runtime for some time, because it seems to exit very fast with just one trace):
[hldebug.zip](https://github.com/vshaxe/hashlink-debugger/files/2245027/hldebug.zip)
It does not connect neither with launch or attach (with manual `hl --debug 6112 --debug-wait out.hl`) commands.

**Comment by ncannasse** [comment]
Thanks there was two fixes required, one in  hld/JitInfo (comparing with 170 instead of 0x170) and another in this repo to use process id because it's not sent by HL 1.6
