### ISSUE TITLE
Unknown identifier for locals

### ISSUE THREAD

**Issue by Gama11** [vshaxe/hashlink-debugger#2]
It seems showing the value for locals doesn't work ("Unknown identifier s")?

![](https://camo.githubusercontent.com/e355752114cd0b6c7a1d96bcdccfeb27ee184a51/68747470733a2f2f692e696d6775722e636f6d2f725630523649582e706e67)

`s` exists in the output with `-D dump=pretty`, so it's not inlined by the analyzer or anything.

_________________

Moved from https://github.com/ncannasse/hashlink-debugger/issues/11

**Comment by ncannasse** [comment]
Thanks, this has been fixed in latest version.
Please note that it requires updating the following with GIT version : haxe, hashlink + update format library to 3.4.1 (just pushed on haxelib)
