### ISSUE TITLE
Debugger does not work on VSCode 1.26

### ISSUE THREAD

**Issue by FuriouZz** [vshaxe/hashlink-debugger#21]
When I try to debug I got an error "Debug adapter process has terminated unexpectedly".

**Comment by septum** [comment]
It's happening to me as well with the same message. It's worth mentioning that it does build the binary.

**Comment by Gaetz** [comment]
Same here with new vscode.

**Comment by septum** [comment]
Downgrading to the v1.25 seems to do the trick for now.

**Comment by ncannasse** [comment]
We build the debugger with native compilation against electron. It seems VSCode has upgraded its electron version, will look into pushing a new release.

**Comment by Gama11** [comment]
In that case, you should make sure to change the required VSCode version to 1.26.0 here, so that the (incompatible) update is not installed for people who are still on 1.25:

https://github.com/vshaxe/hashlink-debugger/blob/2f54d8b52f02d24b38e518e59cf779f1f41e69aa/package.json#L19

**Comment by ncannasse** [comment]
I am currently pushing 0.4.3, should be good :)

**Comment by FuriouZz** [comment]
Thank you =)
