### ISSUE TITLE
Debugger stops working after using any of the step commands (Step Over, Step Into, Step Out)

### ISSUE THREAD

**Issue by ghalle** [vshaxe/hashlink-debugger#22]
Haxe Compiler 4.0.0-preview.4+1e3e5e016
HL/JIT 1.7.0
HashLink Debugger 0.4.3
VSCode 1.27.2 x64
Windows 10 x64

As the title says, not sure if I'm doing anything wrong.

See the following video for reference:
https://i.imgur.com/l0bRHiP.mp4

**Comment by ncannasse** [comment]
Yes I'm aware of the issue, looks like 1.27 broke something in HL debugger
