### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/hashlink-debugger#28]
We don't yet support native debugging on OSX, this library could be helpful in implementing the necessary primitives: https://github.com/blankwall/MacDBG

**Comment by 7sharp9** [comment]
This would be great to have!

**Comment by tsaulic** [comment]
+1 for OSX native debugger! :) Thanks for MacDBG link.

**Comment by 7sharp9** [comment]
Anyone know if this is being worked on?

**Comment by boatincow** [comment]
> Anyone know if this is being worked on?
> […](#)

Hi! Latest update from Nicolas was that one: https://twitter.com/ncannasse/status/1104785779862224897

**Comment by matthewjumpsoffbuildings** [comment]
im also hanging out for this

**Comment by melMass** [comment]
Is it possible to have sys completion on mac using VSCode and Heaps ?

**Comment by varadig** [comment]
+1

**Comment by qkdreyer** [comment]
Waiting for this too !

**Comment by 7sharp9** [comment]
If there was some guidance on how to do this I would partake.

**Comment by ncannasse** [comment]
There's one single thing that needs to be implemented which is the Api.hx version for NodeJS/OSX.
There's already two existing implementations:
NodeDebugApi.hx (Windows)
NodeDebugApiLinux.hx (Linux)
Both use NodeFFI library to load and call system libraries to perform the desired operations, which meanly deals with acting as a native debugger for the target process.

**Comment by opyate** [comment]
@ncannasse If we look at https://github.com/vshaxe/hashlink-debugger/blob/master/hld/Main.hx#L100-L114

Do you mean to end up with 2 new things?

```
		function getAPI() : hld.Api {
			#if hl
			switch( Sys.systemName() ) {
			case "Mac":
				return new hld.HLDebugApiMac(pid, dbg.is64); // NEW
			default:
				return new hld.HLDebugApi(pid, dbg.is64);
			}
			#elseif nodejs
			switch( Sys.systemName() ) {
			case "Windows":
				return new hld.NodeDebugApi(pid, dbg.is64);
			case "Mac":
				return new hld.NodeDebugApiMac(pid, dbg.is64); // NEW
			default:
				return new hld.NodeDebugApiLinux(pid,dbg.is64);
			}
			#else
			throw "This platform does not have a debug API";
			return null;
			#end
		}
```

Because I tried the native (i.e. `#if hl`) debugger on Mac, and it doesn't work:
```

**Comment by ncannasse** [comment]
It depends. 
- if you want the HL commandline debugger to work, you simply need to complete the following file with OSX bindings https://github.com/HaxeFoundation/hashlink/blob/master/src/std/debug.c , you don't need Haxe-level platform switch
- if you want the VSCode debugger to work, you only need the NodeDebugApiMac 

I found that doing the work first in HL then in NodeJS is easier because in C you get compile errors if you mistake the API usage. Then it's more like porting what has been done in C to NodeDebugApiMac

**Comment by rcstuber** [comment]
I am currently on to this subject and now (after literally going through Mach-hell) got a first working draft for the commandline debugger running. Due to how MacOS works it's a lot more verbose (~ 600 lines) compared to the Win/Linux(ptrace) implementation. 

Now when looking at the NodeJS/VSCode Plugin I don't see a re-implementation as a viable option, so I wanted to check what you think about unifying the NodeJS layer by building a shared lib from debug.c as a dependency (per OS platform when installing the plugin) and using NodeFFI to call that implementation? (similar to how HLDebugApi works) 
This way we could have one single source of truth (debug.c) and just a thin layer in the hashlink-debugger. What do you think? 
If you don't want to touch Win/Linux API, let's least do that for Mac, since I believe it also needs to be code-signed anyways for the Kernel APIs to get read/write permissions on processes.

@ncannasse 
@Gama11

**Comment by ncannasse** [comment]
Given things are stable and working on other platforms, I think we can keep
current nodeffi usage for Windows/Linux.
I agree that having a native lib might be the best solution for OSX. You
can setup Makefile so it's built on OSX using VSCode Electron version
(instead of your local nodejs version)

**Comment by rcstuber** [comment]
Ok, great. I will do a pull request for review once I‘m all done. Hopefully no more surprises along the way...

**Comment by rcstuber** [comment]
I am currently looking at an issue with the single-step implementation. I am noticing that single-step register is not reset on several occasions. 

The flow looks as follows:
1. Program hits breakpoint
2. Old code byte is restored at BP position
3. Eip/Rip register is moved back one step
4. Single-step is activated
5. "nextStep" variable is set
If we continue to run, single-step would be produce another break, then single-step register flag would be disabled and the breakpoint restored. Fine so far. HOWEVER...

When being on the breakpoint and clearing all breakpoints and resuming from there, the single-step is not reset. The same goes for starting to do a "Next" step from a hit breakpoint, also the single-step register is still active.
Question is: is this a bug (i.e. missing implementation for OS where single step is not reset automatically) or am I suspending my thread/task too early somehow?

Thanks in advance!

**Comment by ncannasse** [comment]
Yes that's the case on Linux too. Look into Debugger Haxe sources to fix
it, I think I already deal with it there.

**Comment by rcstuber** [comment]
Not sure if you mean this: https://github.com/vshaxe/hashlink-debugger/blob/86315e530042c2bf71a045b3007b08ad8b10e84b/hld/Debugger.hx#L221-L225

I saw that, but that assumes that the Debugger get's a chance to run one more step after hitting the breakpoint, which is not the case when there is no resume() call going on after the BP is hit. So if we hit the breakpoint the thread get's halted and when we then do a next line step it isn't resumed anywhere, so the single-step is still intact whereas it shouldn't be.
Maybe I am missing something here....

**Comment by rcstuber** [comment]
@ncannasse Can you give me a hint where stepping into functions is handled in Debugger.hx? I couldn't yet figure out where and how the next break position is calculated for an ``Into`` step inside the``visitRec()`` function. For me it just seems to break on the calling site and steps over the function instead. Thanks!

Everything else seems working so far.

**Comment by ncannasse** [comment]
With the latest debugger version, we will break on every Call "HL opcode" for StepInto, see https://github.com/vshaxe/hashlink-debugger/blob/master/hld/Debugger.hx#L404
But if we are already on the line and we are trying to "step into" from here, we will set "immediateProcess=true", and enter this loop :

https://github.com/vshaxe/hashlink-debugger/blob/master/hld/Debugger.hx#L474
So basically we are single stepping all x64 opcodes one by one until our stack top changes (enter a function / change line) or we reach a RET (leave a function).

**Comment by ncannasse** [comment]
But given what you are experiencing, and given I explicitly reset SingleStep after each step, it seems might be that your support for disabling singleStep fails. Which is weird as it's used both for setting it and clearing it. you can activate DEBUG to see what's going on in more details.

**Comment by rcstuber** [comment]
Thanks for the info! I have to further debug where exactly the issue is. Writing the registers both for enabling and disabling single stepping seems to work fine. But I still see some problems with the way Single step is handled, if „nextStep“ variable is set to -1 a breakpoint returning from `api.wait()` is not considered as a single step break and if it is set to a code position then a breakpoint (0xCC = Int3) is restored at that memory position. That seems plausible for a real breakpoint, but if we want to just single-step through the x64 instructions then we only need to step and break and do nothing else. The Windows API seems to return a proper Single step code (=2) and already has the single step reset upon returning, but the Linux Api handles it differently?! Again, I might not see the whole picture here...

**Comment by rcstuber** [comment]
***Update***
Stepping into functions now works. I had to check the eflags register when hitting a breakpoint trap and return a the single-step break code instead of the regular breakpoint code in my native implementation. I wonder how - and if even - the Linux API works with that out of the box?

**Comment by ncannasse** [comment]
Interesting... you're right that it's missing in Linux API
implementation... might indeed cause some trouble with current logic. Can
you open a separate issue ? :)

**Comment by rcstuber** [comment]
An odd issue I still have is that when the stack is built in ``makeStack()``, there‘s a RangeError raised, because there‘s an overflow by exactly 8 Bytes.
Any ideas why this could happen? Removing 8 Bytes from the calculated stack size removes this error. But it seems wrong, since apparently on Windows it is working as is.

Here‘s the line it crashes: https://github.com/vshaxe/hashlink-debugger/blob/86315e530042c2bf71a045b3007b08ad8b10e84b/hld/Debugger.hx#L571

**Comment by ncannasse** [comment]
Does doing for( i in 0...(size>>3)-1 ) work for you? This seems correct
actually, since we don't want to read past the stack, I'm just surprise
we're getting into the "if" in the first place.

**Comment by rcstuber** [comment]
Shouldn‘t it be (size-1) >> 3? I have a bit of a hard time following your pointer arithmetics in that function. Here you are adding a pointer length to the stack, maybe that‘s the cause: https://github.com/vshaxe/hashlink-debugger/blob/86315e530042c2bf71a045b3007b08ad8b10e84b/hld/Debugger.hx#L516

**Comment by ncannasse** [comment]
size is in bytes, and we read correctly, but we are checking both  i << 3
and (i+1) << 3 so we should only loop until   (size >> 3) - 1

**Comment by rcstuber** [comment]
Ok, I will try it tomorrow. So would you say it‘s a bug in the current implementation?

One more issue remains (at least I know of): 
When the ``breakOnThrow `` is called when the debugger launches it successfully weites the settings flags, but the next memory read access on the traced process is corrupted and fails. It looks as though it writes something (or somewhere) wrong into the thread info. Any ideas? Is it a race condition or something?

Here‘s the function: https://github.com/vshaxe/hashlink-debugger/blob/86315e530042c2bf71a045b3007b08ad8b10e84b/hld/Debugger.hx#L828

**Comment by ncannasse** [comment]
You can check the flags value. And try setting a different default in HL to
confirm. Maybe some problem with alignment.

**Comment by rcstuber** [comment]
While we wait for an exception (in wait), the NodeJS thread is suspended. When there is no breakpoint set, we wait indefinitely and Node can‘t receive incoming (new) breakpoint requests from VSCode in it‘s event loop, so we are stuck. I see the Windows API has a timeout, the Linux (waitpid) doesn‘t. How should this scenario work in theory?

**Comment by ncannasse** [comment]
Indeed it seems I haven't implemented any timeout on Linux. I guess we
should pass WNOHANG to the waitpid and loop/sleep for the given amount of
time.
Not sure about OSX though.

**Comment by rcstuber** [comment]
Hmmm, okay, I see now that the run loop is executed trough a Timer (in HLAdapter) and Node’s event loop get‘s a chance to run, even though the mail loop is an infinite while. I‘ll check how I can best implement wait timeout on OSX. I think for Linux no hang is an option, but it leaves us with a polling approach.

**Comment by rcstuber** [comment]
I opened two Pull Requests:
#78 
https://github.com/HaxeFoundation/hashlink/pull/367

**Comment by ncannasse** [comment]
Closed by #78 , big thanks to @rcstuber for working on this.

**Comment by rcstuber** [comment]
No problem! Thanks for your support during my journey into CPU registers 🥳

**Comment by 7sharp9** [comment]
Im curious what else needs to happen to try this out?

New version of the vscode extension?

**Comment by rcstuber** [comment]
A new version hasn't been published yet on the VSCode Marketplace. Until that happens you can do try it the manual way like explained here: https://github.com/vshaxe/hashlink-debugger/pull/78#issue-407897390

**Comment by ambethia** [comment]
I just want to say "thank you" to @rcstuber and everyone who put all the work into making this happen. I only dabble in Haxe, and last time I was getting into it, this not working on macOS kind of caused me to hit the brakes and focus on other things in the interim. Looking forward to diving back into Haxe (and Hashlink).
