### ISSUE TITLE
Better tolerance for embedded resources

### ISSUE THREAD

**Issue by tbrosman** [vshaxe/hashlink-debugger#29]
**HashLink debugger version**: 0.4.4
**HashLink version**: 1.7.0 and 1.8.0 (probably earlier as well, but these are the two I tried)
**Haxe version**: 4.0.0-preview.5
**Heaps version**: 1.4.0

I am not sure whether this is something that needs to be fixed in Heaps or the HashLink debugger. I have only had this issue when using the debugger in VS Code (and not when building from the command line), so I'm opening the issue here.

I have a Heaps project with a .gitkeep in my resource directory. This .gitkeep file wasn't completely empty and contained a UTF-16 BOM. When I tried to build or debug the HashLink target from VS Code I got the following non-useful error:

 ```
RangeError: Invalid code point 4186944
```

This would then take me to my launch.json file. A hex dump of my .gitkeep file looks like this:

```
FF FE 0D 00 0A 00
```

(Which strangely doesn't contain the code point mentioned in the error, unless I'm missing something.) I'm guessing this has to do with how Res.initEmbed embeds the resource. For the purpose of a minimal repro, my app looks like this:

```
class PongApp extends App
{
    public static function main()
    {
        Res.initEmbed();
    }
}
```

I haven't looked at the internals too much, but I'm guessing the possible fixes are:

* a) Make Heaps embed the resource in a different way so that arbitrary bytes won't break the debugger.
* b) Change the HashLink debugger to tolerate strange bytes that don't match the encoding scheme it expects (is the debugger looking at the source after macros have transformed it?)

In addition, I would really like error messages for cases where parsing/anything fails when processing an embedded resource. If the error had said something like `Unexpected encoding for res/.gitkeep` it would have made for a much better experience.

**Comment by ncannasse** [comment]
Ok this is quite tricky. HL does encode its bytes in the string table and then JS fails to decode it.
I think I should really modify the HL bytecode format to allow bytes section, but this is quite an important change to make.

**Comment by ncannasse** [comment]
0.5.0 fixes this.
Requires Haxe GIT (will be 4.0-preview 6 or RC) + HL GIT (will be 1.9)

**Comment by tbrosman** [comment]
Awesome! Thank you!
