### ISSUE TITLE
cwd property should be replaced with program path

### ISSUE THREAD

**Issue by Gama11** [vshaxe/hashlink-debugger#3]
A `program` field would be more consistent with other debuggers, and make `cwd` obsolete:

https://github.com/Gama11/HaxeRepro/blob/master/.vscode/launch.json

It would allow it to work with HXML files that have no `-hl`.

___________________

Moved from https://github.com/ncannasse/hashlink-debugger/issues/5

**Comment by Gama11** [comment]
This actually leads to the debugger not working for Lime, which renames the `.hl` file (so it doesn't match the `-hl` from the hxml).

**Comment by ncannasse** [comment]
I think we can close this now?
