### ISSUE TITLE
HandleRequestAsync timeout on launch

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [vshaxe/hashlink-debugger#30]
Hi! When I attempt to launch the debugger, the debugger gets activated, but no executable is run. After a short while I get a Visual Studio Code prompt saying `HandleRequestAsync timeout`.

Here's what I have set up on compile.hxml:

````hxml
-lib heaps
-lib hlsdl
-main Main
-hl hello.hl
````

 `/.vscode/launch.json`:
```json
{
  "version": "0.2.0",
  "configurations": [   
    {
	"name":    "HashLink",
	"request": "launch",
	"type":    "hl",
	"hxml":    "compile.hxml",
	"cwd":     "${workspaceRoot}",
	"preLaunchTask": {
	  "type" : "haxe",
	  "args" : "active configuration"
	}
    }
  ]
}
```

`/.vscode/tasks.json`:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "haxe",
      "args": "active configuration",
      "problemMatcher": [
        "$haxe-absolute",
        "$haxe",
        "$haxe-error",
        "$haxe-trace"
      ],
      "group": {
        "kind":      "build",
        "isDefault": true
      }
    }
  ]
}
```

When I try to run HashLink manually from terminal it runs just fine.

Version/Platform info:

The version of VSCode is 2.0.12
Haxe is 4.0.0-preview.5
HL/JIT 1.9.0
Windows 10

**Comment by ncannasse** [comment]
I think this was fixed in recent versions, closing for now.
