### ISSUE TITLE
Could not start debugger on port 6112

### ISSUE THREAD

**Issue by mundusnine** [vshaxe/hashlink-debugger#35]
I get this error on Ubuntu 18.04.
vscode 1.30
Haxe preview 5
Heaps & all git versions
Hashlink 1.8

Hashlink is compiled by my machine but I changed the location of hl to /usr/bin/ because I would get Failed to spawn hl ENOENT if hl was in /usr/local/bin. 

When I run from terminal hl game.hl the window opens without issue.

When starting the debugger I get the aforementioned output in the Debug console.

**Comment by ncannasse** [comment]
What does   hl --debug 6112 myprogram.hl  does ? (from commandline)

**Comment by mundusnine** [comment]
When starting from the commandline the game/app starts but the debugger doesn't launch. I deduced that the debugger doesn't launch because I put a breakpoint on a trace that gets called in the terminal and it doesn't break before writing to the terminal.

Just to specify I installed the haslink-debugger from the vscode marketplace with the other haxe vscode extensions.

**Comment by mundusnine** [comment]
After I rebooted I got a different behaviour. Instead of giving a Could start... the debug just hanged without  running the app 
![image](https://user-images.githubusercontent.com/29337013/51324846-b8f47f80-1a39-11e9-9686-ef173541d6b4.png)

After that everytime I start the launch nothing happens. For these bugs I used the prelaunchtask with the label "Build". When I tried with the task with label Test I got the first `Could not start debugger on port 6112`bug.



[tasks.txt](https://github.com/vshaxe/hashlink-debugger/files/2769094/tasks.txt)

**Comment by lgut** [comment]
On my linux installation, the debug process is left hanging after the debug session ends. After getting that "Could not start debugger" error try using htop or some other task manager to see if hl is still running with --debug 6112. Killing that solves the issue for me but this shouldn't be necessary.
