### ISSUE TITLE
When using heaps, running the launch task gives an Access Violation. Works from command line

### ISSUE THREAD

**Issue by kfish610** [vshaxe/hashlink-debugger#36]
Even on very simple apps, running them always results in an `Access Violation` Exception on [line 42 of Window.hl.hx](https://github.com/HeapsIO/heaps/blob/6a76ea6922d143d5907c2cee49946a583db0b195/hxd/Window.hl.hx#L42). This doesn't seem to be directly a heaps or hashlink problem, because when running on the command line using hl, it works perfectly, so it seems to just be a vscode debugger problem. Running on hl 1.9.0, haxe 4.0.0-preview.5, heaps 1.5.0, hlsdl 1.8.0, 
uname -a output: `Linux klaptop 4.19.14-1-MANJARO #1 SMP PREEMPT Wed Jan 9 17:17:37 UTC 2019 x86_64 GNU/Linux`,
build.hxml looks like this:
```
-cp src
-main Main
-lib heaps
-lib hlsdl
-hl bin/haxe-testing.hl
```
This bug happens on any heaps program but here is an example
```
class Main extends hxd.App {
    override function init() {
        var tf = new h2d.Text(hxd.res.DefaultFont.get(), s2d);
        tf.text = "Hello World !";
    }
    static function main() {
        new Main();
    }
}
```

**Comment by ncannasse** [comment]
Fixing this will require a bit of extra work on your side :)

First you need to use commandline debugger instead of the vshaxe one, will get more easy to get actual errors. See https://github.com/vshaxe/hashlink-debugger/blob/master/README.md#building-from-source for instructions on how to build it.

Then check if the crash also reproduces. We might want to understand if it's the debugger that is crashing or if it's the app that has the debugger attached.

**Comment by kfish610** [comment]
@ncannasse Followed the instructions and ran `hl debug.hl ~/Documents/Projects/haxe-testing/game.hl`, game ran perfectly. It seems that the problem is indeed in the extension or in vscode somehow.

**Comment by kfish610** [comment]
The only reference to the access violation exception I found anywhere was [this Dead Cells steam forums post](https://steamcommunity.com/app/588650/discussions/2/2592234299534597530/), which is made using hl, haxe, and heaps, so this may be important

**Comment by ncannasse** [comment]
Could you test with the node commandline debugger? It's actually much more near from the VSCode version than the HL one.

**Comment by kfish610** [comment]
@ncannasse I ran it using node, with `node debugger.js ~/Documents/Projects/haxe-testing/bin/haxe-testing.hl`, it once again ran perfectly.

**Comment by ncannasse** [comment]
could you try then fully recompiling from sources and copy the output (including your node_modules) directory into the vscode plugin directory to overwrite marketplace version? It might be some incompatibility between precompiled binaries and your vscode.

**Comment by ncannasse** [comment]
Might be similar to #51, closing
