### ISSUE TITLE
Stepping out of main() takes you to "Unknown file ?"

### ISSUE THREAD

**Issue by Gama11** [vshaxe/hashlink-debugger#39]
```haxe
class Main {
	public static function main() {
		trace("hello world");
	}
}
```

![](https://i.imgur.com/43M1akl.gif)

Also shows up in the callstack - not sure what that's doing there, since `main` _is_ the entry point?

![](https://i.imgur.com/Nnb8Y2A.png)

**Comment by ncannasse** [comment]
Yes we have a "toplevel/boot" method that initialize statics then calls main(), that's the one you can see there. I guess we would need to set its position to before/after Main.main() so the reported positions are not on unknown files.

**Comment by Gama11** [comment]
Stepping out of a function usually sets the position to the `}` anyway in the HL debugger it seems (related: https://github.com/HaxeFoundation/haxe/issues/7767).

**Comment by ncannasse** [comment]
? files are no longer listed in callstacks, but atm stepping out of main() currently still somewhat stall the debugger, will have to investigate another day

**Comment by ncannasse** [comment]
Fixed with my new step implementation.
