### ISSUE TITLE
Unexpected token: "<eof>" when hovering over `new`

### ISSUE THREAD

**Issue by Gama11** [vshaxe/hashlink-debugger#40]
![](https://i.imgur.com/fqUIJ3g.png)

```haxe
class Main {
	static public function main() {
		var a = new Array();
	}
}
```

**Comment by ncannasse** [comment]
Uhm. We're parsing the identifier sent by vscode with hscript. And it can't
parse "new"

Le ven. 8 févr. 2019 19:04, Jens Fischer <notifications@github.com> a
écrit :
