### ISSUE TITLE
Debugger crashes with multiple debug sessions

### ISSUE THREAD

**Issue by Gama11** [vshaxe/hashlink-debugger#41]
When I have two different workspaces open in VSCode, and there's already an HL debug session running in one of them, starting one in the second gives me this error:

![](https://i.imgur.com/cTfS2ym.png)

**Comment by ncannasse** [comment]
Do you use a different debug port ?

**Comment by Gama11** [comment]
Urm.. how would I do that, isn't that hardcoded in the debugger? Shouldn't it figure out a free one on its own like the language server does for `--connect`?

**Comment by ncannasse** [comment]
ATM there is no automatic detection, you need to specify "port" in configuration. But it should give a more meaningful error, and there is a bug related to that (see #37)

**Comment by yuxiaomao** [comment]
Could not reproduce today, and an error message will be displayed if the port is occupied.
