### ISSUE TITLE
Overflow window when launch heaps project

### ISSUE THREAD

**Issue by TheLostX** [vshaxe/hashlink-debugger#46]
![overflow](https://user-images.githubusercontent.com/42852536/53689733-ecb20d00-3d3a-11e9-92b0-5000962d5f26.jpg)

Just running a simple hello world heaps project, VSCode launch that exception. launch from terminal using command "hl file.hl" runs with no problem, build is also ok.

i'm using VSCode latest release x64, Haxe 4.0.0-rc.1 (i tried Haxe 4.0.0-preview.5 too) and hashlink 1.9 (tried 1.8 too)

**Comment by ncannasse** [comment]
Could you send me the file.hl that causes such problem?

**Comment by TheLostX** [comment]
> Could you send me the file.hl that causes such problem?

[hello.zip](https://github.com/vshaxe/hashlink-debugger/files/2923210/hello.zip)

that's the file, also, using HaxeDevelop works fine.

**Comment by Gama11** [comment]
But HaxeDevelop doesn't even support HL debugging? :)

**Comment by TheLostX** [comment]
> But HaxeDevelop doesn't even support HL debugging? :)

yeah i know, i'm just saying to give more details... i tried a lot of things in VSCode and nothing worked, just skip HL Debugger works :/

**Comment by Gama11** [comment]
I was just confused about the "it works fine in HD" statement, considering it's not supported to begin with. ;)

**Comment by ncannasse** [comment]
Could you update to hashlink debugger 0.6.0 which I just released and try again?

**Comment by TheLostX** [comment]
> Could you update to hashlink debugger 0.6.0 which I just released and try again?

Finally working!! Debugger and Game are running fine now, i tested the debugger with some null access, thank you :)!

![hello](https://user-images.githubusercontent.com/42852536/53737953-aceb4280-3e6c-11e9-90af-3a37c3610718.jpg)
