### ISSUE TITLE
"Pause" not working

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/hashlink-debugger#47]
I didn't manage to make "pause" work within VSCode. 

It works very well in commandline debugger when doing `run 0.5` for example (which will run for 0.5s then pause), so I guess this is something related to the order or callbacks within the HLAdapter.

Summoning @Gama11 for help :)

**Comment by ncannasse** [comment]
Ping @Simn @Gama11 : did you manage to have pause working on eval debugger ?

**Comment by Simn** [comment]
This is what I'm doing: https://github.com/vshaxe/eval-debugger/blob/master/src/Main.hx#L310-L315

In the compiler it just sets the state to waiting.

**Comment by ncannasse** [comment]
I managed to make it work but it will only pause if I hit a breakpoint and resume first.
