### ISSUE TITLE
Failed HL Launch with Heaps Using Extension

### ISSUE THREAD

**Issue by glenngartner** [vshaxe/hashlink-debugger#49]
I'm not able to get the Hello Hashlink project (from the Heaps.io getting started site) up and running using this plugin. I am, however, able to run the heaps project starting HL from the command line.

I'm using Windows 10, heaps 1.6.1, haxe 4.0.0-rc.2, hl 1.9 (from pre-built binary). 

When using hlsdl, the game window opens, but remains all white (should be black, with white text). Like this: 

![image](https://user-images.githubusercontent.com/10998599/55276617-6d711400-52bb-11e9-9c0d-63bbee13cde4.png)

 When choosing hldx, receive an exception on DirectXDriver.hx:

![image](https://user-images.githubusercontent.com/10998599/55276605-4286c000-52bb-11e9-9342-eace38c56938.png)

I'm not seeing any problems or errors in the console. Where else can I check for startup issues with this plugin? 

Again, the app runs fine when I run from terminal (for example: hl .\hello.hl) when using both hlsdl and hldx specified in the build.hxml file. In both cases, I see this, as expected:

![image](https://user-images.githubusercontent.com/10998599/55276666-e40e1180-52bb-11e9-8f85-fe3c78307531.png)

my launch.json is the default: 

```json
  {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "HashLink (launch)",
            "request": "launch",
            "type": "hl",
            "hxml": "build.hxml",
            "cwd": "${workspaceFolder}",
            "preLaunchTask": {
                "type": "haxe",
                "args": "active configuration"
            }
        },
        {
            "name": "HashLink (attach)",
            "request": "attach",
            "port": 6112,
            "type": "hl",
            "hxml": "build.hxml",
            "cwd": "${workspaceFolder}",
            "preLaunchTask": {
                "type": "haxe",
                "args": "active configuration"
            }
        }
    ]
}
```
Where should I look next?

**Comment by ncannasse** [comment]
Which graphics card do you have on your computer ? which which driver ?
Do you have some third party software installed that might hook into the graphics driver ? (video recording software, HUD, etc.)

**Comment by ncannasse** [comment]
This seems similar to https://community.heaps.io/t/heaps-with-hashlink-debugger-issue/53/18

**Comment by glenngartner** [comment]
I have a NVidia RTX 2080 max-q. The latest refresh of the Razer Blade 15 series. This is a fresh install of windows. No other software running currently. Not sure of the video driver version, as I'm away from my laptop, but I'll verify and look at that potentially related issue later today.

**Comment by glenngartner** [comment]
Looked at the issue you forwarded, but I don't have a dual integrated and dedicated gpu setup. Just one dedicated Nvidia card.

**Comment by glenngartner** [comment]
Correction to the above. I was wrong about the integrated / dedicated GPU setup. New laptop, still figuring it out. I set my Nvidia 3D settings to prefer the dedicated chipset, and disregard the intel chip, and the plugin works well now. Letting the OS choose a preferred chip created problems for this plugin, as well as other apps. Probably when it tried to select the intel chip. Consider this closed.
