### ISSUE TITLE
Debugger does not launch

### ISSUE THREAD

**Issue by schmidh** [vshaxe/hashlink-debugger#53]
I am using Ubuntu 18.10, hl 1.9.0, haxe 4.0.0-rc.2+77068e1, VS Code 1.33.1. When trying to debug Heaps samples for self-teaching reasons I get following error from VS Code:

`Could not start hl process, executable was not found in PATH. Restart VSCode or computer.`

The build itself works fine. hl is in directory `/usr/local/bin` and causes no problems using from the command line. VS Code has this path also in the `process.env.PATH` variable. No idea why hl cannot be launched. Tried also with haxe 4.0.0.-rc1 because it has been mentioned in the documentation that hashlink is compatible with that version, but no difference.

**Comment by ncannasse** [comment]
Could you check the following ?
Edit the adapter.js, lookup for `js_node_ChildProcess.spawn("hl",hlArgs,{ env : { }, cwd : args.cwd});` and remove the `env : { },` part.

**Comment by ncannasse** [comment]
Uhm, this means it cannot read some variables on stack, and yes there's indeed something not finalized here on 64 bits, but the exception is caught (hence the console trace) and should not prevent the debugger from working unless it causes another error somewhere. I'll try to force it to happen on 32 bits too to see.

**Comment by ncannasse** [comment]
The trace is unrelated as forcing the same error on 32 bit does not affect variable display.
I'll try to test debugging HL64, I haven't tried for some time now.
