### ISSUE TITLE
Allow to specify ENV Path

### ISSUE THREAD

**Issue by kiroukou** [vshaxe/hashlink-debugger#54]
Most debuggers on VsCode allows to specify the "env" attributes on task configuration inside launch.json

That parameter could then be passed to the Node ChildProcess options at spawn call.

The main idea behind that is to be able to specify the version of the HL binary to spawn (when working with multiple versions of haxe & binaries).

Thanks

**Comment by Gama11** [comment]
Wouldn't it be more natural to specify the hl binary directly as an argument in `launch.json`?  I think @jgranick also needs this for the Lime extension.

I guess env is more flexible, but also a bit more awkward for this purpose. Could also have both.

**Comment by kiroukou** [comment]
Could be an option I guess, still les "visual studio code"-ish  in my opinion.

**Comment by ncannasse** [comment]
The `env` launch var is available for some time now.
