### ISSUE TITLE
VSCode Debugger does not work on Linux

### ISSUE THREAD

**Issue by Narice** [vshaxe/hashlink-debugger#56]
Hi,  
I really wanted to try out Heaps and Hashlink with its debugger for VSCode, so I followed the tutorial on Heaps.io but really can't get it working.  
I installed the Hashlink debugger directly from the store.
The debugger starts but the application doesn't and the debugger doesn't stay but seems to crash as it closes instantly.
I can launch the application by doing `hl app.hl` after building it with VSCode.  
I tried launching it with the Hashlink (launch) command on VSCode but it did not work.  
I also tried attaching the VSCode debugger: on the command line, I launched the application with  
`hl --debug 6112 app.hl`  
and then launched the Hashlink (attach) command on VSCode but the debugger seems to also crash this way.

**Comment by JMPJNS** [comment]
@Narice any solutions so far? i have the same problem

**Comment by Narice** [comment]
No, sorry :/

**Comment by ncannasse** [comment]
Could you try with latest VSCode 1.40 + HLDebugger 0.9.0 ?

**Comment by Narice** [comment]
Hey, thank you for your response, I will try it as soon as possible

**Comment by Narice** [comment]
It seems to be working out of the box!
Making a breakpoint, continuing and stopping are working,
However, restarting seems to only close the debugger.
One thing that might not be intended is the fact that stopping stops the debugger but not the application, and I guess that might be related to the restart issue.
Anyway, I'm more than happy to have it working on linux, thank you!

**Comment by Narice** [comment]
using the heaps h2d first example:  
https://heaps.io/documentation/h2d-introduction.html  
I've tested the debugger further and from what I see, Hashlink runs fine without breakpoint but when there are breakpoints, the application remains blank (the screen isn't even cleared to black).  
I'm putting the breakpoint inside the update function.  
The debugger reaches the breakpoint and shows the correct information but Hashlink doesn't display anything which is very strange.  
When continuing, it reaches the second breakpoint, displaying again nothing, but after continuing again, the debugger doesn't even reach the third breakpoint.  
should I close this issue and open another one?

**Comment by ncannasse** [comment]
So one problem is that stopping the debugger doesn't stop the running application.
And for the other I'm not sure exactly what you mean by "does not display anything". Maybe it's not possible to have something displayed while the application is in a breakpoint on Linux ? Try to set a breakpoint on update, remove it and resume.

**Comment by Narice** [comment]
When putting a breakpoint in the update function and launching the application, Hashlink is launched and seems to only do the window creation.  
It does not clear the background to black so the background of the application is the things that were behind the application before launch.  
It sort of captures the desktop at the location where the window was created.  
The background is the screenshot of the desktop where the window opened).  
I'm using the sdl backend and it's exactly the same thing as opening a window in sdl and not clearing the screen to black.  
If I try to disable the breakpoint and continue, the debugger ignores the fact that I've disabled the breakpoint and stops at the deleted breakpoint.  
Continuing again, the program doesn't stop anymore, which is the same behavior as if the breakpoint was not deactivated in the first place.  
I'm using the git version of Hashlink.  
Also, when debugging, the program is not closable, even after the second continuation, so I have to kill Hashlink to spawn a new one.
I hope it helps!

**Comment by ncannasse** [comment]
I think I have fixed some things there, in particular the fact that we didn't kill the process on close. Please try again and report if there's still issues.

**Comment by Narice** [comment]
I have still the same problems with the 1.0.0 version of the hashlink debugger.
The process is not killed when closing the debugger and actually, when the application reaches a breakpoint, the application doesn't continue when I press continue on the debugger. This is why, when putting a breakpoint on the update function, it was causing a non rendered screen, because I guess that the update function comes before the rendering function in heaps and when pressing continue, nothing happened, creating the illusion that no application was actually run and that it couldn't be closed in a normal manner.
I guess the problem resides between the debugger bar and the application or vscode and the application. I hope it helped!
