### ISSUE TITLE
Debugger extension won't launch HashLink in VS Code 1.40

### ISSUE THREAD

**Issue by tbrosman** [vshaxe/hashlink-debugger#64]
HashLink Debugger version: 1.8.0
VS Code version: 1.40

Main.hx:
```haxe
class Main
{
  static function main()
  {
    trace("A");
  }
}
```

build.hxml:
```
-main Main.hx
-hl bin/test.hl
-debug
```

In VS Code 1.39.2, I am able to set a breakpoint on `trace("A")` and HashLink launches/breaks as expected. In VS Code 1.40 HL does not even launch.

**Comment by ncannasse** [comment]
Just released 0.8.1 to support Electron 6 that comes with VSCode 1.40

**Comment by tbrosman** [comment]
@ncannasse I get the same result with 0.8.1. Also, I am not sure how to get debug logs for this. I don't see any errors in any of the Output channels.

**Comment by ncannasse** [comment]
Are you on Windows? Linux?

Le dim. 10 nov. 2019 à 17:51, Tommy Brosman <notifications@github.com> a
écrit :

**Comment by tbrosman** [comment]
@ncannasse Windows 10, x64

**Comment by ncannasse** [comment]
My fault, I forgot to recompile one file :-/ 0.8.2 should have fixed it.

**Comment by tbrosman** [comment]
Works now. Thanks!
