### ISSUE TITLE
ERROR : Unsupported type value 21

### ISSUE THREAD

**Issue by sonygod** [vshaxe/hashlink-debugger#65]
{
	"version": "0.2.0",
	"configurations": [

		{
			"name": "HashLink/JIT",
			"type": "hl",
			"request": "launch",
			//"preLaunchTask": "HL/JIT (debug)",
			"hxml": "buildDebug.hxml",
			"cwd": "${workspaceFolder}",
			"program": "source/sangongD.hl",
			"preLaunchTask": {
				"type" : "haxe",
				"args" : "active configuration"
			}
		}
	]
}

ERROR : Unsupported type value 21

Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\adapter.js line 2007 column 10
Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\adapter.js line 2276 column 26
Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\adapter.js line 9267 column 38
Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\adapter.js line 6061 column 15
Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\adapter.js line 364 column 12
Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\adapter.js line 101 column 29
Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\node_modules\vscode-debugadapter\lib\debugSession.js line 342 column 22
Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\node_modules\vscode-debugadapter\lib\protocol.js line 97 column 38
Called from c:\Users\Administrator\.vscode\extensions\haxefoundation.haxe-hl-0.8.2\node_modules\vscode-debugadapter\lib\protocol.js line 18 column 44
Called from events.js line 200 column 13

**Comment by ncannasse** [comment]
Most likely a mismatch between hl version used to start the executable and haxe version used to compile it.

**Comment by ncannasse** [comment]
If not, please send a reproducible sample.
