### ISSUE TITLE
Snap version of visual studio code has issues with debugger complaining about Dynamic Link Error.

### ISSUE THREAD

**Issue by popgoesme700** [vshaxe/hashlink-debugger#66]
What i experienced is that the snap version of visual studio code seems to break dynamic library linking, or something of the sorts, as when using snap version i always experienced this error, while everything runs fine on the ppa vscode. Could be my linux distro (kubuntu) but i highly think it's something to do with how snap works? Look into it.

**Comment by ncannasse** [comment]
This is possible if they upgraded again the electron version. Look at build
instructions.

Le mar. 28 janv. 2020 à 05:16, popgoesme700 <notifications@github.com> a
écrit :
