### ISSUE TITLE
Easier setup

### ISSUE THREAD

**Issue by gamedevsam** [vshaxe/hashlink-debugger#68]
Getting this to run requires several steps - it would be nice to have a single CLI command that would do it all for us.

**Comment by Gama11** [comment]
Normally you would just install it from the vscode marketplace rather than building it yourself.

**Comment by bhgsbatista** [comment]
Ohh, I thought this was additional setup instructions, didn't realize this was just for people working on the extension. Duh...

**Comment by bhgsbatista** [comment]
Will close this issue when I get home later.
