### ISSUE TITLE
Windows error: 'rm' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by gamedevsam** [vshaxe/hashlink-debugger#69]
```
(cd node_modules/deasync && rm -rf bin && node-gyp rebuild --runtime=electron --target=6.1.2 --disturl=https://atom.io/download/electron)
'rm' is not recognized as an internal or external command,
operable program or batch file.
make: *** [deps] Error 1
```

**Comment by Gama11** [comment]
Hm... I guess the makefile assumes some kind of MinGW / Cygwin installation. But how do you even have `make` to begin with if you don't have `rm`? :)

**Comment by bhgsbatista** [comment]
I installed [make](http://gnuwin32.sourceforge.net/packages/make.htm) :-P

**Comment by ncannasse** [comment]
Cygwin is required for building, but you can modify the makefile to fix this ;)
