### ISSUE TITLE
Assert on "Step inside"

### ISSUE THREAD

**Issue by rboullerne** [vshaxe/hashlink-debugger#81]
```
src/const/Texts.hx:299: Lang : en ==========================
516 shaders loaded in 7.536s
PAD CONNECTED 0
PAD DISCONNECTED 0
PAD CONNECTED 0
src/const/HEditor.hx:46: Lake
src/const/HEditor.hx:46: DeerSpawner
src/const/HEditor.hx:46: GiantSpawner
src/const/HEditor.hx:46: MyrkalfarSpawner
src/const/HEditor.hx:46: KoboldSpawner
***** ERRROR ***** assert
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\adapter.js line 3766 column 10
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\adapter.js line 9920 column 7
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\adapter.js line 6512 column 27
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\adapter.js line 1201 column 25
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\adapter.js line 1188 column 11
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\adapter.js line 1200 column 8
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\node_modules\vscode-debugadapter\lib\debugSession.js line 372 column 22
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\node_modules\vscode-debugadapter\lib\protocol.js line 97 column 38
Called from c:\Users\Rémi\.vscode\extensions\haxefoundation.haxe-hl-1.0.0\node_modules\vscode-debugadapter\lib\protocol.js line 18 column 44
Called from events.js line 203 column 13
```

Northgard revision 17158,
- Put a breakpoint in SelectPlace.hx, line 158 (```var modelName = - Building.getModelNameFromId(bk);```)
- Start Northgard
- Go into the editor and edit a map
- Click the Building tab (not Places)
- Select the Lake
- Breakpoint is triggered, press F11 twice to "step into" 2 times.
- Assert triggers at the second "step into"

**Comment by rcstuber** [comment]
Kindly post issues in english :)

**Comment by rboullerne** [comment]
Oops, my bad ! I work directly with ncannasse, so I just copy pasted what we were discussing from slack. xD

**Comment by rcstuber** [comment]
Might be unrelated, but I had a few occasions where the debugger would step into Std lib code and hang, even though stepping into standard lib should be prevented by the debugger.

**Comment by rcstuber** [comment]
It may have to do with dynamically bound functions: I also have a reproducible bug, where the Debugger oddly jumps into `Date.hx` at line 0 and triggers an Assert even though it should step into a dynamic function which was previously rebound. Seems like the Debugger is doing some function resolution wrongly.

<img width="896" alt="bug" src="https://user-images.githubusercontent.com/1127643/82231882-1cdcd000-992e-11ea-80a6-77686ebfd4bc.png">
