### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by NQNStudios** [vshaxe/hashlink-debugger#82]
Are there usage instructions somewhere I'm missing? Can they be added to the README.md and info page in the VSCode extension browser?

I mean just on a simple level, how do I launch my project and interact with the debugger. Do I need to add a launch configuration like with the hxcpp debugger? What does that configuration look like?

I also tried searching the command palette for anything related to the extension and didn't find anything.

**Comment by rcstuber** [comment]
If you installed the extension properly, it should let you create a launch.json for the Hashlink environment or add said configuration automatically. You should best have the Haxe extension pack installed: https://marketplace.visualstudio.com/items?itemName=vshaxe.haxe-extension-pack
<img width="530" alt="VSHaxe" src="https://user-images.githubusercontent.com/1127643/83612016-1aab8000-a582-11ea-88bd-32b819a29e7e.png">


Below is what get's created. Then it's just like using any other VSCode debugger.
```
// launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "HashLink (launch)",
            "request": "launch",
            "type": "hl",
            "cwd": "${workspaceFolder}",
            "preLaunchTask": {
                "type": "haxe",
                "args": "active configuration"
            }
        },
        {
            "name": "HashLink (attach)",
            "request": "attach",
            "port": 6112,
            "type": "hl",
            "cwd": "${workspaceFolder}",
            "preLaunchTask": {
                "type": "haxe",
                "args": "active configuration"
            }
        }
    ]
}

```

**Comment by rcstuber** [comment]
Can this be closed?

**Comment by NQNStudios** [comment]
yeah, thanks
