### ISSUE TITLE
Can't compile with 1.1 of hashlink-debugger

### ISSUE THREAD

**Issue by phelioz** [vshaxe/hashlink-debugger#84]
Hi!

The hashlink_debugger is great but with the 1.1.0 update I have run into some problems.

I can't compile with hashlink-debugger 1.1.0 anymore. 
When trying to compile any project with 1.1.0 it says:
"Please use a Haxe configuration that targets HashLink (found target "none")"

In the launch.json the "hxml" property is not recognized.
Does this have to do with the "added closures stack (requires HL 1.12+)".

Can't you use the extension with 1.1 Hashlink? If it is that then it would be nice with a new binary release of 1.12.

It works again if I switch back to 1.0.0 version of hashlink-debugger.

Running Windows 10.

**Comment by Gama11** [comment]
You need to select a "Haxe Configuration" (usually a HXML file) that targets HL in the status bar.

**Comment by phelioz** [comment]
Thanks for the fast help, that fixed it :) Strange it must have auto picked it before.
