### ISSUE TITLE
Return value cannot be inspected

### ISSUE THREAD

**Issue by rcstuber** [vshaxe/hashlink-debugger#92]
The debugger never shows value being returned from a function like most debuggers do for other languages.

(tested only on MacOS)

**Comment by ncannasse** [comment]
I'm open to implement that but I'm not sure how it works on the VSCode side. Any insight would be appreciated.
ping @nadako

**Comment by ncannasse** [comment]
I have added it as a `(return)` local.

**Comment by rcstuber** [comment]
Cool, thanks! 😊
