### ISSUE TITLE
Your Hashlink executable is not properly codesigned

### ISSUE THREAD

**Issue by grayaii** [vshaxe/hashlink-debugger#94]
I'm getting the following error when I try "Run->Run without Debugging" in VSCode.

```
Your Hashlink executable is not properly codesigned.
Run `make codesign_osx` during Hashlink installation.
Path: hl
```

I installed Hashlink by:

```
git clone https://github.com/HaxeFoundation/hashlink.git
cd hashlink/
brew bundle
make codesign_osx (enter password)
make
make install
```
The revision of hashlink that i've cloned is:
```
$ git rev-parse --verify HEAD
f33b3f88150e107e7f7e96917cde51246906d477
```
Kinda weird, that I get this error:
```
$ codesign -d --entitlements - /usr/local/bin/hl
/usr/local/bin/hl: code object is not signed at all
```

**Comment by grayaii** [comment]
Right after posting this, I re-ran those steps over and over, but codesign kept failing.

I completely removed it by `make uninstall` and re-running those steps and it worked.

I think I must have run `make install` initially, just to see if the compilation worked, and THEN ran `make codesign_osx`, followed by `make install`.  Huh.
Well, I'll close this out then.

**Comment by rcstuber** [comment]
From your original post it sounds like you ran `make codesign_osx` before running `make`, which is the wrong order.
