### ISSUE TITLE
HL debugger no longer works in latest vscode 

### ISSUE THREAD

**Issue by deepnight** [vshaxe/hashlink-debugger#97]
Absolutely nothing happens. Builds and tasks still run, but running debugger just does nothing anymore. It worked just fine before this morning update :)

**VScode**
```
Version: 1.56.0 (system setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by rcstuber** [comment]
Confirming same issue for Mac. Let's have a look...

Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.2.0

**Comment by ncannasse** [comment]
@Gama11 any insight on what might be causing this ?

**Comment by rcstuber** [comment]
When running the debug extension adapter on a custom port and connecting via `debugServer: 4711` everything works fine. VSCode throws no errors in any of its logs, at least none that I found.

**Comment by kLabz** [comment]
Gama11 on discord:
> it often needs an update on electron updates since it bundles some dependencies that are linked against a specific version

**Comment by deepnight** [comment]
> When running the debug extension adapter on a custom port and connecting via `debugServer: 4711` everything works fine. VSCode throws no errors in any of its logs, at least none that I found.

How do you change that? 🤔

**Comment by rcstuber** [comment]
@deepnight  It requires you to have the hashlink-debugger project locally.  See my response here: https://github.com/vshaxe/hashlink-debugger/issues/96#issuecomment-823853835

**Comment by ncannasse** [comment]
> it often needs an update on electron updates since it bundles some dependencies that are linked against a specific version
> https://github.com/vshaxe/hashlink-debugger/blob/master/Makefile#L2

I tried to upgrade to Electron 12 but it didn't work out. Looking into @rcstuber solution to understand what's going on here.

**Comment by ncannasse** [comment]
I've located the issue which is related to ffi-napi module loading but I can't make it to work so I posted a message here
https://github.com/node-ffi-napi/node-ffi-napi/issues/156

**Comment by rcstuber** [comment]
Nice catch! Haven't been able to try myself, but maybe there is some useful info here apart from the usual electron rebuild step: https://www.electronjs.org/docs/tutorial/using-native-node-modules

**Comment by ncannasse** [comment]
@rcstuber took a few hours to figure things out, turned it was an old incompatible ffi-napi version :'( . Could you rebuild the OSX bindings and update the prebuild in Makefile so I can make a release ?

**Comment by rcstuber** [comment]
Oh shuuut, I could have saved you those hours if I hadn't forgotten to actually run `haxe build.hxml`after pulling a clean repo into my extensions folder :-/ Sorry!

**Comment by rcstuber** [comment]
I created a PR https://github.com/vshaxe/hashlink-debugger/pull/99. I removed the steps to copy the ffi-napi and ref-napi native extensions, since those new releases should come pre-bundled with these prebuilds via NPM.
This also includes the fixes needed to properly compile under Haxe 4.2.1.  –– did you not stumbled upon this error yet? @ncannasse

**Comment by ncannasse** [comment]
@rcstuber actually it seems I can run perfectly fine with the prebuilt without any requirement for native builds, so I have cleanup Makefile and push a new version, which should work on all OS out of the box. Can you confirm it works on OSX ?

**Comment by rcstuber** [comment]
Are you sure you haven't got files lying around? Because the deasync module does not ship with any prebuild *.node files and would require a node-gyp build step afaik.

**Comment by ncannasse** [comment]
It does in my install

**Comment by rcstuber** [comment]
@ncannasse Yes works, I updated my reply. If that's the case you could also adapt the README for manual installation to simply run `npm install`.

**Comment by deepnight** [comment]
Where can we get the fixed build? 🤔

**Comment by ncannasse** [comment]
If you update to vscode 1.56 it will install (v 1.1.2)

Le jeu. 13 mai 2021 à 16:35, Sébastien Bénard ***@***.***> a
écrit :

**Comment by deepnight** [comment]
👌

**Comment by hammeron-art** [comment]
I'm with the same issue in vscode 1.57.1 and hashlink-debugger 1.1.2. It builds but nothing happens after it.
